### ISSUE TITLE
crash on login

### ISSUE THREAD

**Issue by Grogdor** [fredp613/voipsms#1]
iPhone 5c running iOS 9.2.1, upon entering a valid login/password, app crashes to desktop shortly after authenticating. Relaunching crashes right away at title screen. Please let me know if you need the full crash report.

{"bug_type":"109","os_version":"iPhone OS 9.2.1 (13D15)","timestamp":"2016-04-02 19:06:28.28 -0600","build_version":"3.1.0","app_name":"VOIPsms","bundleID":"com.myclerical.VOIPsms","name":"VOIPsms","is_first_party":false,"app_version":"1.5","share_with_app_devs":false,"slice_uuid":"","adam_id":1037874743}
Incident Identifier: 
CrashReporter Key:  
Hardware Model:      iPhone5,3
Process:            VOIPsms [1647]
Path:                /private/var/mobile/Containers/Bundle/Application//VOIPsms.app/VOIPsms
Identifier:          com.myclerical.VOIPsms
Version:            3.1.0 (1.5)
Code Type:          ARM (Native)
Parent Process:      launchd [1]

Date/Time:          2016-04-02 19:06:28.28 -0600
Launch Time:        2016-04-02 19:06:27.27 -0600
OS Version:          iOS 9.2.1 (13D15)
Report Version:      105

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000000e7ffdefe
Triggered by Thread:  3

Filtered syslog:
None found

Global Trace Buffer (reverse chronological seconds):
0.574608    CFNetwork                0x0000000024998325 TCP Conn 0x16db5130 started
0.575696    CFNetwork                0x0000000024998325 TCP Conn 0x16dce960 started
0.589489    CFNetwork                0x00000000249d8957 Creating default cookie storage with default identifier
0.589489    CFNetwork                0x00000000249d8933 Faulting in CFHTTPCookieStorage singleton
0.589489    CFNetwork                0x0000000024a1aaa7 Faulting in NSHTTPCookieStorage singleton

**Comment by fredp613** [comment]
Issue fixed on master branch. This issue arose because the voip.ms api only allows syncing up to 91 days of messages. Upon first log in my app attempts to download all of your messages therefore if you are a voip.ms user for more than 91 days, the api returns an invalid response which crashes the app since I didnt write the corresponding code to act on that error. I fixed this issue on the master branch in the latest commit by mutating the "frmDate" variable to max 80 days regardless of registration date unless the registration date was less than 91 days from app open. Update sent to apple

**Comment by Grogdor** [comment]
Updating via App Store was still crashing, but uninstalling and reinstalling did the trick, working fine now, thanks!
